### ISSUE TITLE
Problem with default exports

### ISSUE THREAD

**Issue by jarecsni** [shmoop207/appolo-inject#4]
Say I have a module like this:

export default class M {
}

and I have a definition for this like below:
{
        path: "./M",
        singleton: true,
        lazy: true
}

I get an exception from inject.js saying object is not a function. I tried forking your library and changing the code to this:

```
       try {
            //crate object instance
            if (typeof objectDefinition.type === 'object') {
                objectDefinition.type = objectDefinition.type.default;
            }
            newObjectInstance = new objectDefinition.type(...argumentInstances);            
        }
        catch (e) {
            throw new Error("Injector failed to create object objectID:" + objectID + "' \n" + e);
        }

```

This way it works, not sure if I could achieve this without modifying your lib?

Thanks.

**Comment by uditalias** [comment]
Hey @jarecsni 
Can you please provide full code sample?

**Comment by jarecsni** [comment]
I tried to add a unit test to your project to reproduce this issue, but it doesn't work with  ES6 (and the problem is explicitly related to the default export in ES6).

Since the problem involves loading classes from the path, it's not easy to create a snippet somewhere like JSBin or CodePen either.

So all I can do I'm afraid is to provide more details:

1) I have my definitions in a JSON file (I think it's cleaner to keep the container configuration in a separate file). It looks like this:

```
{
    "projectService": {
        "path": "./project/ProjectService",
        "singleton": true,
        "inject": ["projectWebService"],
        "lazy": true
    },
    "projectWebService": {
        "path": "./project/ProjectWebService",
        "singleton": true,
        "lazy": true
    }
}

```

This is how I configure the injector:

```
this._injector = inject.createContainer();
this._injector.addDefinitions(moduledef);
this._injector.initialize({
   root: process.cwd() + '/app'
});

```

Relative to the IoC.json definitions file I have a project subfolder, with the two classes in it:

```
class ProjectService {
}
...
export default ProjectService;

```
and

```
class ProjectWebApiService {
}
...
export default ProjectWebApiService;
```

If I run this with your original code, I get an exception:

Error: Injector failed to create object objectID:projectService' 
      TypeError: object is not a function

 The error was thrown at: 
          at Injector._createObjectInstance (/.../node_modules/appolo-inject/lib/inject.js:168:19),
          at Injector.get (/.../node_modules/appolo-inject/lib/inject.js:45:29),

This is obviously happening because the export (module.exports) is an object, with the 'default' attribute on it according to the ES6 module spec (as far as I know).

I could fix it by replacing your original:

```
    //convert path to type
        if (objectDefinition.path) {
            objectDefinition.type = require(path.join(this._options.root, objectDefinition.path + '.js'));
        }

```

with this:
```
        if (objectDefinition.path) {
            objectDefinition.type = require(path.join(this._options.root, objectDefinition.path + '.js'));
            if (typeof objectDefinition.type === 'object') {
                objectDefinition.type = objectDefinition.type.default;
            }
        }
```

I think it would be fairly important to add this, as currently the injector cannot load ES6 default exports.

Thanks!

**Comment by jarecsni** [comment]
Actually, there is an even bigger problem... require with variable name does not at all work in a React Native environment. The only way I managed to get it working was using the new import() 'function' (which is Stage 3 T39), but the pain there is that it makes getting a bean out of the container an async function. Would be good to get appolo-inject working in React Native, do you have any plans for that (otherwise I'll have to keep using my fork).

**Comment by jarecsni** [comment]
Some more detail on what doesn't work with require:

```
console.log('resolving [' + m + ']'); (m === '@app/project/ProjectService')
let x = require('@app/project/ProjectService');
console.log('x', x); // works
let result = require(m); // blows up
console.log('res', result);
```

**Comment by jarecsni** [comment]
Guys, I think it's ok to close this issue. The real issue is with React Native packager, not appolo-inject which fully supports lazy importing modules ('path' attribute). Thanks!
